# Generated by Django 4.1.7 on 2023-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('time', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='assessment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('BG', 'Beginner'), ('AT', 'Amateur'), ('PF', 'Professional')], default='BG', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.ManyToManyField(to='tutorial.outcomes'),
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(related_name='topic_courses', to='tutorial.topic'),
        ),
    ]
