# Generated by Django 4.1.7 on 2023-12-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_outcomes_topic_course_assessment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic'},
        ),
    ]
