# Generated by Django 4.1.7 on 2023-12-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcomes',
            options={'verbose_name': 'Outcome'},
        ),
    ]
