# Generated by Django 4.1.7 on 2023-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_alter_outcomes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
