# Generated by Django 4.1.7 on 2024-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_teacher_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='time',
        ),
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
