# Generated by Django 4.1.7 on 2024-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_remove_topic_time_topic_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
