# Generated by Django 4.1.7 on 2024-02-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_topic_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['index'], 'verbose_name': 'Topic'},
        ),
    ]
