# Generated by Django 4.1.7 on 2024-02-24 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='index',
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='tutorial.course'),
        ),
    ]
