# Generated by Django 4.1.7 on 2024-02-25 04:37

from django.db import migrations
import tutorial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_video_text_image_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Topic'},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=tutorial.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=tutorial.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
