# Generated by Django 4.2.7 on 2024-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_remove_course_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='duration',
        ),
        migrations.AddField(
            model_name='topic',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
